-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 15:02:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scudo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scudo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scudo_db` DEFAULT CHARACTER SET utf8 ;
USE `scudo_db` ;

-- -----------------------------------------------------
-- Table `scudo_db`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`User` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`User` (
  `id_user` INT NOT NULL,
  `fullname` VARCHAR(250) NULL,
  `username` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `biography` VARCHAR(1000) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `image` VARCHAR(250) NULL,
  `role` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scudo_db`.`Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`Resource` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`Resource` (
  `id_resource` INT NOT NULL,
  `id_user` INT NOT NULL,
  `filename` VARCHAR(250) NULL,
  `title` VARCHAR(250) NOT NULL,
  `text` VARCHAR(500) NULL,
  `longitude` DECIMAL(65) NULL,
  `latitude` DECIMAL(65) NULL,
  `type` VARCHAR(250) NOT NULL,
  `is_private` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  `published_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_resource`),
  CONSTRAINT `FK_Resource_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Resource_User_idx` ON `scudo_db`.`Resource` (`id_user` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`Group` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`Group` (
  `id_group` INT NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scudo_db`.`Conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`Conversation` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`Conversation` (
  `id_conversation` INT NOT NULL,
  `id_sender` INT NOT NULL,
  `id_recipient` INT NOT NULL,
  `is_established` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_conversation`),
  CONSTRAINT `FK_Conversation_User_Sender`
    FOREIGN KEY (`id_sender`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Conversation_User_Recipient`
    FOREIGN KEY (`id_recipient`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Conversation_User_Sender_idx` ON `scudo_db`.`Conversation` (`id_sender` ASC);

CREATE INDEX `FK_Conversation_User_Recipient_idx` ON `scudo_db`.`Conversation` (`id_recipient` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`Message` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`Message` (
  `id_message` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_conversation` INT NOT NULL,
  `content` VARCHAR(5000) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_message`),
  CONSTRAINT `FK_Message_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Message_Conversation`
    FOREIGN KEY (`id_conversation`)
    REFERENCES `scudo_db`.`Conversation` (`id_conversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Message_User_idx` ON `scudo_db`.`Message` (`id_user` ASC);

CREATE INDEX `FK_Message_Conversation_idx` ON `scudo_db`.`Message` (`id_conversation` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`User_Follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`User_Follow` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`User_Follow` (
  `id_user` INT NOT NULL,
  `id_user_followed` INT NOT NULL,
  CONSTRAINT `FK_User-Follow_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_User-Follow_User2`
    FOREIGN KEY (`id_user_followed`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_User-Follow_User_idx` ON `scudo_db`.`User_Follow` (`id_user` ASC);

CREATE INDEX `FK_User-Follow_User2_idx` ON `scudo_db`.`User_Follow` (`id_user_followed` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`User_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`User_Group` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`User_Group` (
  `id_user` INT NOT NULL,
  `id_group` INT NOT NULL,
  `role` VARCHAR(250) NOT NULL,
  CONSTRAINT `FK_User-Group_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_User-Group_Group`
    FOREIGN KEY (`id_group`)
    REFERENCES `scudo_db`.`Group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_User-Group_User_idx` ON `scudo_db`.`User_Group` (`id_user` ASC);

CREATE INDEX `FK_User-Group_Group_idx` ON `scudo_db`.`User_Group` (`id_group` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`Resource_Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`Resource_Group` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`Resource_Group` (
  `id_resource` INT NOT NULL,
  `id_group` INT NOT NULL,
  CONSTRAINT `FK_Resource-Group_Resource`
    FOREIGN KEY (`id_resource`)
    REFERENCES `scudo_db`.`Resource` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Resource-Group_Group`
    FOREIGN KEY (`id_group`)
    REFERENCES `scudo_db`.`Group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Resource-Group_Resource_idx` ON `scudo_db`.`Resource_Group` (`id_resource` ASC);

CREATE INDEX `FK_Resource-Group_Group_idx` ON `scudo_db`.`Resource_Group` (`id_group` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`Comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`Comment` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`Comment` (
  `id_comment` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_resource` INT NOT NULL,
  `content` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comment`),
  CONSTRAINT `FK_Comment_User`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Comment_Resource`
    FOREIGN KEY (`id_resource`)
    REFERENCES `scudo_db`.`Resource` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Comment_User_idx` ON `scudo_db`.`Comment` (`id_user` ASC);

CREATE INDEX `FK_Comment_Resource_idx` ON `scudo_db`.`Comment` (`id_resource` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
