-- MySQL Script generated by MySQL Workbench
-- Thu Feb  9 15:02:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema scudo_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scudo_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scudo_db` DEFAULT CHARACTER SET utf8 ;
USE `scudo_db` ;

-- -----------------------------------------------------
-- Table `scudo_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`user` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`user` (
  `id_user` INT NOT NULL,
  `fullname` VARCHAR(250) NULL,
  `username` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `biography` VARCHAR(1000) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `image` VARCHAR(250) NULL,
  `role` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scudo_db`.`resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`resource` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`resource` (
  `id_resource` INT NOT NULL,
  `id_user` INT NOT NULL,
  `filename` VARCHAR(250) NULL,
  `title` VARCHAR(250) NOT NULL,
  `text` VARCHAR(500) NULL,
  `longitude` DECIMAL(65) NULL,
  `latitude` DECIMAL(65) NULL,
  `type` VARCHAR(250) NOT NULL,
  `is_private` TINYINT(1) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  `published_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_resource`),
  CONSTRAINT `FK_resource_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_resource_user_idx` ON `scudo_db`.`resource` (`id_user` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`group` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`group` (
  `id_group` INT NOT NULL,
  `name` VARCHAR(250) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `image` VARCHAR(250) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scudo_db`.`conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`conversation` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`conversation` (
  `id_conversation` INT NOT NULL,
  `id_sender` INT NOT NULL,
  `id_recipient` INT NOT NULL,
  `is_established` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_conversation`),
  CONSTRAINT `FK_conversation_user_Sender`
    FOREIGN KEY (`id_sender`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_conversation_user_Recipient`
    FOREIGN KEY (`id_recipient`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_conversation_user_Sender_idx` ON `scudo_db`.`conversation` (`id_sender` ASC);

CREATE INDEX `FK_conversation_user_Recipient_idx` ON `scudo_db`.`conversation` (`id_recipient` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`message` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`message` (
  `id_message` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_conversation` INT NOT NULL,
  `content` VARCHAR(5000) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_message`),
  CONSTRAINT `FK_message_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_message_conversation`
    FOREIGN KEY (`id_conversation`)
    REFERENCES `scudo_db`.`conversation` (`id_conversation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_message_user_idx` ON `scudo_db`.`message` (`id_user` ASC);

CREATE INDEX `FK_message_conversation_idx` ON `scudo_db`.`message` (`id_conversation` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`user_follow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`user_follow` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`user_follow` (
  `id_user` INT NOT NULL,
  `id_user_followed` INT NOT NULL,
  CONSTRAINT `FK_user-follow_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_user-follow_user2`
    FOREIGN KEY (`id_user_followed`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_user-follow_user_idx` ON `scudo_db`.`user_follow` (`id_user` ASC);

CREATE INDEX `FK_user-follow_user2_idx` ON `scudo_db`.`user_follow` (`id_user_followed` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`user_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`user_group` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`user_group` (
  `id_user` INT NOT NULL,
  `id_group` INT NOT NULL,
  `role` VARCHAR(250) NOT NULL,
  CONSTRAINT `FK_user-group_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_user-group_group`
    FOREIGN KEY (`id_group`)
    REFERENCES `scudo_db`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_user-group_user_idx` ON `scudo_db`.`user_group` (`id_user` ASC);

CREATE INDEX `FK_user-group_group_idx` ON `scudo_db`.`user_group` (`id_group` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`resource_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`resource_group` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`resource_group` (
  `id_resource` INT NOT NULL,
  `id_group` INT NOT NULL,
  CONSTRAINT `FK_resource-group_resource`
    FOREIGN KEY (`id_resource`)
    REFERENCES `scudo_db`.`resource` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_resource-group_group`
    FOREIGN KEY (`id_group`)
    REFERENCES `scudo_db`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_resource-group_resource_idx` ON `scudo_db`.`resource_group` (`id_resource` ASC);

CREATE INDEX `FK_resource-group_group_idx` ON `scudo_db`.`resource_group` (`id_group` ASC);


-- -----------------------------------------------------
-- Table `scudo_db`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `scudo_db`.`comment` ;

CREATE TABLE IF NOT EXISTS `scudo_db`.`comment` (
  `id_comment` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_resource` INT NOT NULL,
  `content` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_comment`),
  CONSTRAINT `FK_comment_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `scudo_db`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_comment_resource`
    FOREIGN KEY (`id_resource`)
    REFERENCES `scudo_db`.`resource` (`id_resource`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_comment_user_idx` ON `scudo_db`.`comment` (`id_user` ASC);

CREATE INDEX `FK_comment_resource_idx` ON `scudo_db`.`comment` (`id_resource` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
